import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";
const sidebars: SidebarsConfig = {
  APIReferenceSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
